/**
 * Integration test — AUTONOMOUS AGENT (Epic 3) against the Firestore emulator.
 *
 * Drives the real `/agent/run` orchestration end-to-end through one call:
 *   POST /login → POST /agent/run (learn → extract-skills → design → plan →
 *   verified build) → GET /agent/runs/:id
 *
 * Self-skip: gated on `EMULATOR_AVAILABLE` via `describe.skipIf` (shared harness)
 * so the default `npm test` (no emulator) stays green and only the CI emulator
 * job runs it.
 *
 * AI / network mocking: identical seams to `e2e_intent.test.ts` — the production
 * module graph keeps `ai.ts` resolution + the SSRF guard real, and only the two
 * network calls are intercepted with `vi.mock` (test-only):
 *   - `src/providers/openai` → deterministic embeddings + an LLM stub that
 *     branches on the system prompt to return the JSON/text each step expects
 *     (extract-skills array / plan object / build object / design prose).
 *   - `src/ssrf` → `readUrl`/`crawlSite` return canned page text so ingestion
 *     never hits the network. Nothing under `functions/src/**` is modified.
 */
import { describe, it, expect, beforeAll, afterAll, vi } from "vitest";

const FAKE_PAGE_TEXT =
  "GHOST Agent Builder is an autonomous engineering platform. It learns from " +
  "sources, extracts reusable skills, designs an architecture, plans the work " +
  "and then builds real project files with idempotent, well-validated code.";

vi.mock("../../src/providers/openai", async (importOriginal) => {
  const actual = (await importOriginal()) as typeof import("../../src/providers/openai");
  const vector = () => [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8];
  return {
    ...actual,
    openaiEmbedding: vi.fn(async (_apiKey: string, _input: string) => vector()),
    openaiEmbeddingBatch: vi.fn(async (_apiKey: string, inputs: string[]) => inputs.map(() => vector())),
    openaiTest: vi.fn(async (_apiKey: string) => undefined),
    openaiLlm: vi.fn(async (_apiKey: string, system: string, _user: string, _temperature?: number) => {
      if (system.includes("reusable engineering skills")) {
        return JSON.stringify([
          {
            skillName: "Idempotent Writes",
            description: "Make every write operation safely retryable to avoid duplicate side effects.",
            example: "Use a deterministic request id as the document id so retries upsert.",
            appliesTo: ["firestore", "typescript"],
            template: "const ref = db.collection('x').doc(requestId);"
          }
        ]);
      }
      if (system.includes('"prompts"')) {
        return JSON.stringify({
          files: [{ path: "OVERVIEW.md", content: "# Overview\n\nProject overview and goals." }],
          prompts: [{ title: "Orchestrator", content: "You are the orchestrator agent. Coordinate sub-agents to completion." }]
        });
      }
      if (system.includes('"summary"')) {
        return JSON.stringify({
          files: [
            { path: "README.md", content: "# Demo\n\nGenerated by the agent run." },
            { path: "index.ts", content: "export const hello = (): string => 'world';\n" },
            { path: "package.json", content: JSON.stringify({ name: "demo", version: "1.0.0", private: true }, null, 2) }
          ],
          summary: "Generated a minimal, self-contained demo project."
        });
      }
      return "## Дизайн\n1) Цель: автономная сборка.\n2) Модули.\n3) Архитектура.\nРиски и следующий шаг.";
    })
  };
});

vi.mock("../../src/ssrf", async (importOriginal) => {
  const actual = (await importOriginal()) as typeof import("../../src/ssrf");
  return {
    ...actual,
    readUrl: vi.fn(async (_url: string) => ({ title: "Agent Source", text: FAKE_PAGE_TEXT })),
    crawlSite: vi.fn(async (url: string) => [{ url, title: "Agent Source", text: FAKE_PAGE_TEXT }])
  };
});

import { EMULATOR_AVAILABLE, startServer, seedLoginUser, type TestServer } from "../helpers/harness";

describe.skipIf(!EMULATOR_AVAILABLE)("integration: autonomous agent (/agent/run)", () => {
  let srv: TestServer;
  let restoreKey: () => void;

  beforeAll(async () => {
    const prev = process.env.OPENAI_API_KEY;
    process.env.OPENAI_API_KEY = "sk-agent-fake-key";
    restoreKey = () => {
      if (prev === undefined) delete process.env.OPENAI_API_KEY;
      else process.env.OPENAI_API_KEY = prev;
    };
    srv = await startServer();
  });

  afterAll(async () => {
    await srv.close();
    restoreKey();
    vi.restoreAllMocks();
  });

  function aiBlocked(res: { status: number; body: any }, label: string): boolean {
    if (res.status === 400 && res.body?.error === "no_api_key") {
      console.warn(`[agent] '${label}' returned no_api_key — AI seam not mocked; skipping AI-dependent asserts.`);
      return true;
    }
    return false;
  }

  it("rejects unauthenticated access (401)", async () => {
    const res = await srv.request("POST", "/agent/run", { body: { urls: ["https://example.com/x"], task: "Build it" } });
    expect(res.status).toBe(401);
  });

  it("validates the body (>=1 url, task length)", async () => {
    const creds = await seedLoginUser("agent-pw-123");
    const login = await srv.request("POST", "/login", { body: { username: creds.username, password: creds.password } });
    const token = login.body.token as string;
    const res = await srv.request("POST", "/agent/run", { token, body: { urls: [], task: "x" } });
    expect(res.status).toBe(400);
  });

  it("runs the full autonomous cycle and exposes the run via GET", async () => {
    const creds = await seedLoginUser("agent-pw-456");
    const login = await srv.request("POST", "/login", { body: { username: creds.username, password: creds.password } });
    expect(login.status).toBe(200);
    const token = login.body.token as string;

    const run = await srv.request("POST", "/agent/run", {
      token,
      body: { urls: ["https://example.com/guide", "https://example.com/guide2"], task: "Build an autonomous agent platform in TypeScript with Firestore" }
    });
    if (aiBlocked(run, "agent/run")) return;

    expect(run.status).toBe(200);
    expect(typeof run.body.runId).toBe("string");
    expect(typeof run.body.topicId).toBe("string");
    expect(typeof run.body.projectId).toBe("string");
    expect(typeof run.body.buildRunId).toBe("string");
    expect(Array.isArray(run.body.files)).toBe(true);
    expect(run.body.files.length).toBeGreaterThanOrEqual(1);
    // Verification ran without an infra error.
    expect(run.body.verification).toBeTruthy();
    expect(run.body.verification.status).not.toBe("error");
    // Steps recorded the whole pipeline.
    const stepNames = (run.body.steps as { name: string }[]).map((s) => s.name);
    expect(stepNames).toEqual(expect.arrayContaining(["learning", "skilling", "designing", "planning", "building"]));

    // GET the run (owner-scoped) and confirm it reached "ready".
    const got = await srv.request("GET", `/agent/runs/${run.body.runId}`, { token });
    expect(got.status).toBe(200);
    expect(got.body.run.id).toBe(run.body.runId);
    expect(got.body.run.status).toBe("ready");

    // A different user cannot read this run.
    const other = await seedLoginUser("agent-pw-789");
    const otherLogin = await srv.request("POST", "/login", { body: { username: other.username, password: other.password } });
    const otherToken = otherLogin.body.token as string;
    const denied = await srv.request("GET", `/agent/runs/${run.body.runId}`, { token: otherToken });
    expect(denied.status).toBe(404);
  });
});
